version: "3.7"
services:
  api:
    container_name: apiscore
    restart: always
    build: ./phase2
    image: marathon:dev
    ports:
      - 5000:5000 # 5000:5000
    entrypoint: /bin/sh -c "uvicorn  prediction:app --host 0.0.0.0 --port 5000"
    deploy:
      replicas: 7

  server:
    container_name: server_nginx13
    restart: always
    build: ./nginx
    ports:
      - 5040:5040 # 5040:5040
    depends_on:
      - api